title: M17 CS 506 Contemporary issues in computing...
description: Hello, I am TUSIIME B WILLIAMS(MAY17/COMP/005U), a Masters student at UTAMU, Uganda .

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Issues
   url: /index.html
 - title: Ransom Ware
   url: /ransom
 - title: Systems
   url: /systems
 - title: Big Data
   url: /contact

social:
   github: tuba-willis
   twitter: tubawillis
   facebook: 
   linkedin: Tusiime B Williams
   email: tubawillis@gmail.com

google_analytics: "UA-58263416-1"
